### ISSUE TITLE
Kanban board setup

### ISSUE THREAD

**Issue by virag-ky** [virag-ky/Free-To-Play-Games#21]
### In this group project, it's two of us: @virag-ky and @SaidRasinlic .

**https://github.com/virag-ky/Free-To-Play-Games/projects/1**

**Comment by brytebee** [comment]
Hi, @virag-ky & @SaidRasinlic👋,

Good job so far coming so far with the progress you've made! 💪💪

## Highlights
You have done amazing in the following:
- Added a link. ✔️
- Listed the team members. ✔️
- Successfully copied the Kanban board. ✔️
 
However, there are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/VL48WGMDjD64umCEkv/giphy.gif)

# Required Changes ♻️

- [ ] **Required:** Kindly change the link to lead to [the project](https://github.com/virag-ky/Free-To-Play-Games/projects/1), ie . `[link](https://github.com/virag-ky/Free-To-Play-Games/projects/1)`
- [ ] **Required:** Kindly assign all tasks to a team member including group tasks as should in this diagram.

![image](https://user-images.githubusercontent.com/27709832/163820076-eb4f26f9-0ad2-4075-b0dc-c68c1c123d31.png)

- [ ] **Required:** Assign tasks fairly to the team members.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Please, remember to tag me in your question so I can receive the notification.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
